apps/proveedor/urls.py
from django.conf.urls import url 
from django.contrib.auth.decorators import login_required
from apps.proveedor.views import index
from apps.proveedor.views import proveedor_view, proveedor_list, proveedor_edit, proveedor_delete, \
	proveedorList,proveedorCreate,proveedorUpdate, proveedorDelete





urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(proveedorCreate.as_view()) , name='proveedor_crear'),
	url(r'^listar$',login_required(proveedorList.as_view()) , name='proveedor_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(proveedorUpdate.as_view()) , name='proveedor_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(proveedorDelete.as_view()) , name='proveedor_eliminar'),


]

tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^proveedor/', include('apps.proveedor.urls', namespace="proveedorIndex")),
    url(r'^producto/', include('apps.producto.urls', namespace="productoIndex")),
    url(r'^cliente/', include('apps.cliente.urls', namespace="clienteIndex")),
    url(r'^compra/', include('apps.compra.urls', namespace="compraIndex")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuarioIndex")),
    url(r'^', login, {'template_name':'index.html'}, name='login'),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/proveedor/models.py
from django.db import models

# Create your models here.

class Proveedor(models.Model):
    NombreProveedor = models.CharField(max_length=35)
    Ruc = models.CharField(max_length=11)
    Direccion = models.CharField(max_length=35)
    Telefono = models.CharField(max_length=9)
    DatosEncargado = models.CharField(max_length=35)
    TelefonoEncargado = models.CharField(max_length=9)
    FechaRegistro = models.DateField()



    def NombreCompleto(self):
        cadena = "{0} {1}, {2}"
        return cadena.format(self.NombreProveedor, self.Telefono, self.Direccion)

    def __str__(self):
        return self.NombreCompleto()

apps/proveedor/forms.py
from django import forms
from apps.proveedor.models import Proveedor


class proveedorForm(forms.ModelForm):
	class Meta:
		model = Proveedor

		fields = [
			'NombreProveedor',
			'Ruc',
			'Direccion',
			'Telefono',
			'DatosEncargado',
			'TelefonoEncargado',
			'FechaRegistro',

		]

		labels = {
			'NombreProveedor':'Nombre del Probeedor',
			'Ruc':'Ruc',
			'Direccion':'Direccion',
			'Telefono':'Telefono',
			'DatosEncargado':'Nombre Encargado',
			'TelefonoEncargado':'Telefono Encargado',
			'FechaRegistro':'Fecha Registro',

		}	

		widgets = {
			'NombreProveedor':forms.TextInput(attrs={'class':'form-control'}),
			'Ruc': forms.TextInput(attrs={'class':'form-control'}),
			'Direccion': forms.TextInput(attrs={'class':'form-control'}),
			'Telefono': forms.TextInput(attrs={'class':'form-control'}),
			'DatosEncargado': forms.TextInput(attrs={'class':'form-control'}),
			'TelefonoEncargado': forms.TextInput(attrs={'class':'form-control'}),
			'FechaRegistro': forms.TextInput(attrs={'class':'form-control'}),
		}

apps/proveedor/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from apps.proveedor.forms import proveedorForm

from apps.proveedor.models import Proveedor

# Create your views here.

def index(request):
	return render(request, 'proveedor/index.html')


def proveedor_view(request):
    if request.method == 'POST':
        form = proveedorForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('proveedorIndex:index')
    else:
        form = proveedorForm()

    return render(request, 'proveedor/proveedor_form.html', {'form':form})

def proveedor_list(request):
    proveedor = Proveedor.objects.all()
    contexto = {'proveedores':proveedor}
    return render(request, 'proveedor/proveedor_list.html', contexto)

def proveedor_edit(request, id_proveedor):
    proveedor = Proveedor.objects.get(id=id_proveedor)
    if request.method == 'GET':
        form = proveedorForm(instance=proveedor)
    else:
        form = proveedorForm(request.POST, instance=proveedor)
        if form.is_valid():
            form.save()
        return redirect('proveedorIndex:proveedor_listar')
    return render(request, 'proveedor/proveedor_form.html', {'form':form})

def proveedor_delete(request, id_proveedor):
    proveedor = Proveedor.objects.get(id=id_proveedor)
    if request.method == 'POST':
        proveedor.delete()
        return redirect('proveedorIndex:proveedor_listar')
    return render(request, 'proveedor/proveedor_delete.html', {'proveedores':proveedor})


class proveedorList(ListView):
    model = Proveedor
    template_name = 'proveedor/proveedor_list.html'

class proveedorCreate(CreateView):
    model = Proveedor
    form_class = proveedorForm
    template_name = 'proveedor/proveedor_form.html'
    success_url = reverse_lazy('proveedorIndex:proveedor_listar')

class proveedorUpdate(UpdateView):
    model = Proveedor
    form_class = proveedorForm
    template_name = 'proveedor/proveedor_form.html'
    success_url = reverse_lazy('proveedorIndex:proveedor_listar')

class proveedorDelete(DeleteView):
    model = Proveedor
    form_class = proveedorForm
    template_name = 'proveedor/proveedor_delete.html'
    success_url = reverse_lazy('proveedorIndex:proveedor_listar')

templates/proveedor/index.html
{% extends 'base/base.html' %}

{% block title %}
App Proveedor
{% endblock %}


{% block content %}
<h1>Contenido de la aplicacion Proveedor</h1>
{% endblock %}

templates/proveedor/proveedor_delete.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h3>¿Deseas Eliminar el Registro de {{ object.Proveedor }}?</h3>
        <button type="submit" class="btn btn-danger">Si, eliminar</button>
       {#  <a class= "btn btn-default" href="{% url 'almacenIndex:almacen_listar' %}">Cancelar</a> #}
    </form>
{% endblock %}

templates/proveedor/proveedor_form.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger center-block">Guardar</button>
    </form>
{% endblock %}

templates/proveedor/proveedor_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>
			<td>#</td>
			<td>Nombre Proveedor</td>
			<td>Ruc</td>
			<td>Direccion</td>
			<td>Telefono</td>
            <td>Nombres Encargado</td>
            <td>Telefono encargado</td>
            <td>Fecha Ingreso</td>
            <td>Opciones</td>
            
		</tr>
	</thead>
	<tbody>
        {% if object_list %}
        {% for proveedor in object_list %}
		<tr>
			<td>{{ proveedor.id }}</td>
			<td>{{ proveedor.NombreProveedor }}</td>
            <td>{{ proveedor.Ruc }}</td>
			<td>{{ proveedor.Direccion }}</td>
            <td>{{ proveedor.Telefono }}</td>
            <td>{{ proveedor.DatosEncargado }}</td>
            <td>{{ proveedor.TelefonoEncargado }}</td>
            <td>{{ proveedor.FechaRegistro }}</td>


            <td>
                <a class="btn btn-primary" href="{% url 'proveedorIndex:proveedor_editar' proveedor.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'proveedorIndex:proveedor_eliminar' proveedor.id %}">Eliminar</a>
            </td>
		</tr>
        {% endfor %}
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
	</tbody>
</table>
{% endblock%}