apps/cliente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.cliente.views import index
from apps.cliente.views import cliente_view, cliente_list, cliente_edit, cliente_delete, \
    clienteList,clienteCreate,clienteUpdate, clienteDelete


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(clienteCreate.as_view()) , name='cliente_crear'),
	url(r'^listar$',login_required(clienteList.as_view()) , name='cliente_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(clienteUpdate.as_view()) , name='cliente_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(clienteDelete.as_view()) , name='cliente_eliminar'),

]

tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^proveedor/', include('apps.proveedor.urls', namespace="proveedorIndex")),
    url(r'^producto/', include('apps.producto.urls', namespace="productoIndex")),
    url(r'^cliente/', include('apps.cliente.urls', namespace="clienteIndex")),
    url(r'^compra/', include('apps.compra.urls', namespace="compraIndex")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuarioIndex")),
    url(r'^', login, {'template_name':'index.html'}, name='login'),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/cliente/models.py
from django.db import models

# Create your models here.

class Cliente (models.Model):
    Nombre = models.CharField(max_length=25)
    Apellidos = models.CharField(max_length=25, null=True, blank=True)
    DNI = models.CharField(max_length=8, null=True)
    Sexo = models.CharField(max_length=10)

    def Cliente(self):
        cadena = "{0}, {1} "
        return cadena.format(self.Nombre, self.DNI)

    def __str__(self):
        return self.Cliente()

apps/cliente/forms.py
from django import forms
from apps.cliente.models import Cliente

class clienteForm(forms.ModelForm):
    class Meta:
        model = Cliente

        fields = [
            'Nombre',
            'Apellidos',
            'DNI',
            'Sexo',
        ]

        labels = {
            'Nombre':'Nombres',
            'Apellidos':'Apellidos',
            'DNI':'DNI',
            'Sexo':'Sexo',
        }

        widgets = {
            'Nombre':forms.TextInput(attrs={'class': 'form-control'}),
            'Apellidos':forms.TextInput(attrs={'class': 'form-control'}),
            'DNI':forms.TextInput(attrs={'class': 'form-control'}),
            'Sexo':forms.TextInput(attrs={'class': 'form-control'}),
        }

apps/cliente/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.cliente.forms import clienteForm
from apps.cliente.models import Cliente
from django.shortcuts import render

# Create your views here.

def index(request):
	return render(request, 'cliente/index.html')


def cliente_view(request):
    if request.method == 'POST':
        form = clienteForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('clienteIndex:index')
    else:
        form = clienteForm()

    return render(request, 'cliente/cliente_form.html', {'form':form})

def cliente_list(request):
    cliente = Cliente.objects.all()
    contexto = {'clientes':cliente}
    return render(request, 'cliente/cliente_list.html', contexto)

def cliente_edit(request, id_cliente):
    cliente = Cliente.objects.get(id=id_cliente)
    if request.method == 'GET':
        form = clienteForm(instance=cliente)
    else:
        form = clienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
        return redirect('clienteIndex:cliente_listar')
    return render(request, 'cliente/cliente_form.html', {'form':form})

def cliente_delete(request, id_cliente):
    cliente = Cliente.objects.get(id=id_cliente)
    if request.method == 'POST':
        cliente.delete()
        return redirect('clienteIndex:cliente_listar')
    return render(request, 'cliente/cliente_delete.html', {'clientes':cliente})


class clienteList(ListView):
    model = Cliente
    template_name = 'cliente/cliente_list.html'

class clienteCreate(CreateView):
    model = Cliente
    form_class = clienteForm
    template_name = 'cliente/cliente_form.html'
    success_url = reverse_lazy('clienteIndex:cliente_listar')

class clienteUpdate(UpdateView):
    model = Cliente
    form_class = clienteForm
    template_name = 'cliente/cliente_form.html'
    success_url = reverse_lazy('clienteIndex:cliente_listar')

class clienteDelete(DeleteView):
    model = Cliente
    form_class = clienteForm
    template_name = 'cliente/cliente_delete.html'
    success_url = reverse_lazy('clienteIndex:cliente_listar')

templates/cliente/cliente_delete.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h3>¿Deseas Eliminar el Registro de {{ object.Cliente }}?</h3>
        <button type="submit" class="btn btn-danger">Si, eliminar</button>
       {#  <a class= "btn btn-default" href="{% url 'almacenIndex:almacen_listar' %}">Cancelar</a> #}
    </form>
{% endblock %}

templates/cliente/cliente_form.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger center-block">Guardar</button>
    </form>
{% endblock %}

templates/cliente/cliente_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>

			<td>#</td>
			<td>Nombre</td>
			<td>Apellidos</td>
            <td>DNI</td>
            <td>Sexo</td>
            <td>Opciones</td>

		</tr>
	</thead>
	<tbody>
        {% if object_list %}
        {% for cliente in object_list %}
		<tr>
			<td>{{ cliente.id }}</td>
            <td>{{ cliente.Nombre }}</td>
            <td>{{ cliente.Apellidos }}</td>
            <td>{{ cliente.DNI }}</td>
            <td>{{ cliente.Sexo }}</td>

            <td>
                <a class="btn btn-primary" href="{% url 'clienteIndex:cliente_editar' cliente.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'clienteIndex:cliente_eliminar' cliente.id %}">Eliminar</a>
            </td>
		</tr>
        {% endfor %}
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
	</tbody>
</table>
{% endblock%}

templates/cliente/index.html
{% extends 'base/base.html' %}

{% block title %}
App Cliente
{% endblock %}


{% block content %}
<h1>Contenido de la aplicacion Cliente</h1>
{% endblock %}