apps/cliente/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.cliente.views import index
from apps.cliente.views import cliente_view, cliente_list, cliente_edit, cliente_delete, \
    clienteList,clienteCreate,clienteUpdate, clienteDelete


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(clienteCreate.as_view()) , name='cliente_crear'),
	url(r'^listar$',login_required(clienteList.as_view()) , name='cliente_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(clienteUpdate.as_view()) , name='cliente_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(clienteDelete.as_view()) , name='cliente_eliminar'),

]

apps/compra/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.compra.views import index
from apps.compra.views import compra_view, compra_list, compra_edit, compra_delete, \
    compraList,compraCreate,compraUpdate, compraDelete


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(compraCreate.as_view()) , name='compra_crear'),
	url(r'^listar$',login_required(compraList.as_view()) , name='compra_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(compraUpdate.as_view()) , name='compra_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(compraDelete.as_view()) , name='compra_eliminar'),

]

apps/producto/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.producto.views import index
from apps.producto.views import producto_view, producto_list, producto_edit, producto_delete, \
    productoList,productoCreate,productoUpdate, productoDelete


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(productoCreate.as_view()) , name='producto_crear'),
	url(r'^listar$',login_required(productoList.as_view()) , name='producto_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(productoUpdate.as_view()) , name='producto_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(productoDelete.as_view()) , name='producto_eliminar'),


]

apps/proveedor/urls.py
from django.conf.urls import url 
from django.contrib.auth.decorators import login_required
from apps.proveedor.views import index
from apps.proveedor.views import proveedor_view, proveedor_list, proveedor_edit, proveedor_delete, \
	proveedorList,proveedorCreate,proveedorUpdate, proveedorDelete





urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(proveedorCreate.as_view()) , name='proveedor_crear'),
	url(r'^listar$',login_required(proveedorList.as_view()) , name='proveedor_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(proveedorUpdate.as_view()) , name='proveedor_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(proveedorDelete.as_view()) , name='proveedor_eliminar'),


]

tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^proveedor/', include('apps.proveedor.urls', namespace="proveedorIndex")),
    url(r'^producto/', include('apps.producto.urls', namespace="productoIndex")),
    url(r'^cliente/', include('apps.cliente.urls', namespace="clienteIndex")),
    url(r'^compra/', include('apps.compra.urls', namespace="compraIndex")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuarioIndex")),
    url(r'^', login, {'template_name':'index.html'}, name='login'),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	{% block extrastatic %}
	{% endblock %}

	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<title>{% block title %}Document {% endblock %}</title>
</head>
<body>
<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
                        <ul>
                            <li><a href="{% url 'proveedorIndex:proveedor_crear' %}">Crear Proveedor</a></li>
                            <li><a href="{% url 'productoIndex:producto_crear' %}">Crear Producto</a></li>
                            <li><a href="{% url 'clienteIndex:cliente_crear' %}">Crear Cliente</a></li>
                            <li><a href="{% url 'compraIndex:compra_crear' %}">Crear Compra</a></li>
                        </ul>
                        <ul>
                            <li><a href="{% url 'proveedorIndex:proveedor_listar' %}">Listar Proveedor</a></li>
                            <li><a href="{% url 'productoIndex:producto_listar' %}">Listar Producto</a></li>
                            <li><a href="{% url 'clienteIndex:cliente_listar' %}">Listar Cliente</a></li>
                            <li><a href="{% url 'compraIndex:compra_listar' %}">Listar Compar</a></li>
                        </ul>
                        <ul>
                            <li><a href="{% url 'logout' %}">SALIR</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
	{% endblock %}


	{% block content %}
	<h4>	Bloque de contenido		</h4>
	{% endblock %}


	{% block footer %}
	{% endblock%}
</div>
	<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

	{% block extrajs %}
	{% endblock %}


</body>
</html>