apps/producto/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from apps.producto.views import index
from apps.producto.views import producto_view, producto_list, producto_edit, producto_delete, \
    productoList,productoCreate,productoUpdate, productoDelete


urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^nuevo$',login_required(productoCreate.as_view()) , name='producto_crear'),
	url(r'^listar$',login_required(productoList.as_view()) , name='producto_listar'),
	url(r'^editar/(?P<pk>\d+)/$',login_required(productoUpdate.as_view()) , name='producto_editar'),
	url(r'^eliminar/(?P<pk>\d+)/$',login_required(productoDelete.as_view()) , name='producto_eliminar'),


]

tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import login, logout_then_login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^proveedor/', include('apps.proveedor.urls', namespace="proveedorIndex")),
    url(r'^producto/', include('apps.producto.urls', namespace="productoIndex")),
    url(r'^cliente/', include('apps.cliente.urls', namespace="clienteIndex")),
    url(r'^compra/', include('apps.compra.urls', namespace="compraIndex")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuarioIndex")),
    url(r'^', login, {'template_name':'index.html'}, name='login'),

    url(r'^accounts/login/', login, {'template_name':'index.html'}, name='login'),

    url(r'^logout/', logout_then_login, name='logout'),
    url(r'^reset/password_reset', password_reset, 
        {'template_name':'registration/password_reset_form.html',
        'email_template_name': 'registration/password_reset_email.html'}, 
        name='password_reset'), 
    url(r'^password_reset_done', password_reset_done, 
        {'template_name': 'registration/password_reset_done.html'}, 
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, 
        {'template_name': 'registration/password_reset_confirm.html'},
        name='password_reset_confirm'
        ),
    url(r'^reset/done', password_reset_complete, {'template_name': 'registration/password_reset_complete.html'},
        name='password_reset_complete'),
]

apps/producto/models.py
from django.db import models
from apps.compra.models import Compra

# Create your models here.

class Producto(models.Model):
    Nombre = models.ForeignKey(Compra, null=False, blank=False, on_delete=models.CASCADE)
    PrecioVenta = models.DecimalField(max_digits=6, decimal_places=2)
    PrecioVentaCaja = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)
    Detalle = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):

        return "{0} {1}".format(self.Nombre, self.PrecioVenta)

apps/producto/forms.py
from django import forms
from apps.producto.models import Producto


class productoForm(forms.ModelForm):
    class Meta:
        model = Producto

        fields = [
            'Nombre',
            'PrecioVenta',
            'PrecioVentaCaja',
            'Detalle',


        ]

        labels = {
            'Nombre':'Producto',
            'PrecioVenta':'Precio venta Unidad',
            'PrecioVentaCaja':'Precio venta caja',
            'Detalle':'Detalle',

        }

        widgets = {
            'Nombre': forms.Select(attrs={'class': 'form-control'}),
            'PrecioVenta': forms.TextInput(attrs={'class': 'form-control'}),
            'PrecioVentaCaja': forms.TextInput(attrs={'class': 'form-control'}),
            'Detalle': forms.TextInput(attrs={'class': 'form-control'}),

        }

apps/producto/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from apps.producto.forms import productoForm
from apps.producto.models import Producto

# Create your views here.

def index(request):
	return render(request, 'producto/index.html')


def producto_view(request):
    if request.method == 'POST':
        form = productoForm(request.POST)
        if form.is_valid():
            form.save()
        return redirect('productoIndex:index')
    else:
        form = productoForm()

    return render(request, 'producto/producto_form.html', {'form':form})

def producto_list(request):
    producto = Producto.objects.all()
    contexto = {'productos':producto}
    return render(request, 'producto/producto_list.html', contexto)

def producto_edit(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    if request.method == 'GET':
        form = productoForm(instance=producto)
    else:
        form = productoForm(request.POST, instance=producto)
        if form.is_valid():
            form.save()
        return redirect('productoIndex:producto_listar')
    return render(request, 'producto/producto_form.html', {'form':form})

def producto_delete(request, id_producto):
    producto = Producto.objects.get(id=id_producto)
    if request.method == 'POST':
        producto.delete()
        return redirect('productoIndex:producto_listar')
    return render(request, 'producto/producto_delete.html', {'productos':producto})


class productoList(ListView):
    model = Producto
    template_name = 'producto/producto_list.html'

class productoCreate(CreateView):
    model = Producto
    form_class = productoForm
    template_name = 'producto/producto_form.html'
    success_url = reverse_lazy('productoIndex:producto_listar')

class productoUpdate(UpdateView):
    model = Producto
    form_class = productoForm
    template_name = 'producto/producto_form.html'
    success_url = reverse_lazy('productoIndex:producto_listar')

class productoDelete(DeleteView):
    model = Producto
    form_class = productoForm
    template_name = 'producto/producto_delete.html'
    success_url = reverse_lazy('productoIndex:producto_listar')

templates/producto/index.html
{% extends 'base/base.html' %}

{% block title %}
App Producto
{% endblock %}


{% block content %}
<h1>Contenido de la aplicacion Producto</h1>
{% endblock %}

templates/producto/producto_delete.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        <h3>¿Deseas Eliminar el Registro de {{ object.Producto }}?</h3>
        <button type="submit" class="btn btn-danger">Si, eliminar</button>
       {#  <a class= "btn btn-default" href="{% url 'almacenIndex:almacen_listar' %}">Cancelar</a> #}
    </form>
{% endblock %}

templates/producto/producto_form.html
{% extends 'base/base.html' %}
{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-danger center-block">Guardar</button>
    </form>
{% endblock %}

templates/producto/producto_list.html
{% extends 'base/base.html' %}

{% block content %}

<table class="table table-bordered">
	<thead>
		<tr>

			<td>#</td>
			<td>Nombre Producto</td>
			<td>Precio Venta</td>
            <td>Precio Paquete</td>
            <td>Detalle</td>

		</tr>
	</thead>
	<tbody>
        {% if object_list %}
        {% for producto in object_list %}
		<tr>
			<td>{{ producto.id }}</td>
            <td>{{ producto.Nombre }}</td>
            <td>{{ producto.PrecioVenta }}</td>
            <td>{{ producto.PrecioVentaCaja }}</td>
            <td>{{ producto.Detalle }}</td>

            <td>
                <a class="btn btn-primary" href="{% url 'productoIndex:producto_editar' producto.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'productoIndex:producto_eliminar' producto.id %}">Eliminar</a>
            </td>
		</tr>
        {% endfor %}
        {% else %}
        <h1>No hay registros</h1>
        {% endif %}
	</tbody>
</table>
{% endblock%}